JobApplicationBoard/ViewModels/CreateRoleViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace JobApplicationBoard.ViewModels
{
    public class CreateRoleViewModel
    {
        [Required]
        [Display(Name ="Role name")]
        public string RoleName { get; set; }
    }
}

JobApplicationBoard/ViewModels/EditRoleViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace JobApplicationBoard.ViewModels
{
    public class EditRoleViewModel
    {
        public EditRoleViewModel()
        {
            Users = new List<string>();
        }
        public string Id { get; set; }

        [Required(ErrorMessage = "Please enter a role name.")]
        [Display(Name = "Role name")]
        public string RoleName { get; set; }

        public List<string> Users { get; set; }
    }
}

JobApplicationBoard/ViewModels/EditRolesViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace JobApplicationBoard.ViewModels
{
    public class EditRolesViewModel
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Please enter a role name.")]
        [Display(Name ="Role name")]
        public string RoleName { get; set; }

        public List<string> Users { get; set; }
    }
}

JobApplicationBoard/Controllers/RolesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using JobApplicationBoard.Models;
using JobApplicationBoard.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace JobApplicationBoard.Controllers
{
    [Authorize]
    public class RolesController : Controller
    {
        private readonly RoleManager<IdentityRole> roleManager;
        private readonly UserManager<AppUser> userManager;

        public RolesController(RoleManager<IdentityRole> roleManager, UserManager<AppUser> userManager)
        {
            this.roleManager = roleManager;
            this.userManager = userManager;
        }


        [Route("/roles")]
        public IActionResult Index()
        {
            var roles = roleManager.Roles;
            return View(roles);
        }

        [HttpGet]
        [Route("/roles/create-role")]
        public IActionResult CreateRole()
        {
            return View();
        }


        [HttpPost]
        [Route("/roles/create-role")]
        public async Task<IActionResult> CreateRoleAsync(CreateRoleViewModel model) //Creates a new identity role
        {
            if (ModelState.IsValid)
            {
                IdentityRole identityRole = new IdentityRole
                {
                    Name = model.RoleName
                };

                IdentityResult result = await roleManager.CreateAsync(identityRole);

                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }

                foreach(IdentityError error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
            }
            return View(model);
        }

        [HttpGet]
        [Route("/roles/edit-role")]
        public async Task<IActionResult> EditRole(string id) //Edits identity role
        {
            var role = await roleManager.FindByIdAsync(id);

            // If the id is invalid, shows 404 page
            if(role == null)
            {
                return View("error404");
            }

            // Updates model with role
            var model = new EditRoleViewModel
            {
                Id = role.Id,
                RoleName = role.Name,

            };

            foreach(var user in userManager.Users)
            {
                if(await userManager.IsInRoleAsync(user, role.Name))
                {
                    model.Users.Add(user.UserName);
                }
            }


            return View(model);
        }

        [HttpPost]
        [Route("/roles/edit-role")]
        public async Task<IActionResult> EditRole(EditRoleViewModel model) //Edits identity role
        {
            var role = await roleManager.FindByIdAsync(model.Id);

            // If the id is invalid, shows 404 page
            if (role == null)
            {
                return View("error404");
            }
            else
            {
                role.Name = model.RoleName;
                var result = await roleManager.UpdateAsync(role);

                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }

                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }


                return View(model);
            }

            
        }

        [HttpGet]
        [Route("roles/manage-role-users")]
        public async Task<IActionResult> ManageRoleUsers(string roleId)
        {
            ViewBag.roleId = roleId;

            var role = await roleManager.FindByIdAsync(roleId);

            if (role == null)
            {
                return View("error404");
            }

            var model = new List<UserRoleViewModel>();

            foreach(var user in userManager.Users)
            {
                var userViewModel = new UserRoleViewModel
                {
                    UserId = user.Id,
                    UserName = user.UserName
                };

                if (await userManager.IsInRoleAsync(user, role.Name))
                {
                    userViewModel.IsChecked = true;
                }
                else
                {
                    userViewModel.IsChecked = false;
                }

                model.Add(userViewModel);
            }

            return View(model);
        }

        [HttpPost]
        [Route("roles/manage-role-users")]
        public async Task<IActionResult> ManageRoleUsers(List<UserRoleViewModel> model, string roleid)
        {
            var role = await roleManager.FindByIdAsync(roleid);

            if(role == null)
            {
                return View("error404");
            }

            for(int i = 0; i < model.Count; i++)
            {
                var user = await userManager.FindByIdAsync(model[i].UserId);

                IdentityResult result = null;

                if(model[i].IsChecked && !(await userManager.IsInRoleAsync(user, role.Name)))
                {
                    result = await userManager.AddToRoleAsync(user, role.Name);
                } 
                else if (!model[i].IsChecked && await userManager.IsInRoleAsync(user, role.Name))
                {
                    result = await userManager.RemoveFromRoleAsync(user, role.Name);
                }
                else
                {
                    continue;
                }

                if (result.Succeeded)
                {
                    if (i < (model.Count - 1))
                        continue;
                    else
                        return RedirectToAction("EditRole", new { id = roleid });
                }

            }

            return RedirectToAction("EditRole", new { id = roleid });
        }

    }
}

JobApplicationBoard/Views/Roles/CreateRole.cshtml
@model CreateRoleViewModel

@{
    ViewData["Title"] = "Create Role";
}


<section class="col-10 col-sm-9 col-md-8 col-lg-6 mx-auto py-4">
    <form asp-controller="Roles" asp-action="CreateRole" method="post">
        <h2 class="text-center text-primary">@ViewData["Title"]</h2>
        <hr />
        <div class="form-group">
            <label asp-for="RoleName"></label>
            <input asp-for="RoleName" class="form-control" />
            <span asp-validation-for="RoleName" class="text-danger"></span>
        </div>
        <div asp-validation-summary="All" class="text-danger"></div>
        <div class="form-group mb-3">
            <button type="submit" class="btn btn-primary btn-block">Save Role</button>
        </div>
    </form>
</section>

JobApplicationBoard/Views/Roles/EditRole.cshtml
@model EditRoleViewModel
@{
    ViewData["Title"] = "Edit role";
}


<section class="col-10 col-sm-9 col-md-6 col-lg-5 mx-auto py-4">
    <form asp-controller="Roles" asp-action="EditRole" method="post">
        <header>
            <h2 class="text-center text-primary">@ViewData["Title"]</h2>
            <h6>Id: @Model.Id</h6>
            <hr />
        </header>
        <div class="form-group d-none">
            <label asp-for="Id"></label>
            <input asp-for="Id" contenteditable="false" class="form-control"/>
        </div>

        <div class="form-group">
            <label asp-for="RoleName"></label>
            <input asp-for="RoleName" class="form-control" />
            <span asp-validation-for="RoleName" class="text-danger"></span>
        </div>

        <div asp-validation-summary="All" class="text-danger"></div>

        <div class="form-group row mt-3 px-4">
            <button type="submit" class="btn btn-primary mr-2">Save changes</button>
            <a asp-action="Index" asp-controller="Roles" class="btn btn-outline-danger">Discard changes</a>
        </div>

        <div class="card">
            <div class="card-header">
                <h3>Users</h3>
            </div>
            <div class="card-body">
                @if (Model.Users.Any())
                {
                    foreach (var user in Model.Users)
                    {
                        <p>@user</p>
                    }
                }
                else
                {
                    <p class="text-muted">No users is assigned to this role</p>
                }
            </div>
            <div class="card-footer">
                <a asp-action="ManageRoleUsers" 
                   asp-controller="Roles"  asp-route-roleid="@Model.Id" class="btn btn-primary mr-2">Manage users</a>
            </div>
        </div>

    </form>
</section>

JobApplicationBoard/Views/Roles/Index.cshtml
@model IEnumerable<IdentityRole>

@{
    ViewData["Title"] = "All Roles";
}

<section class="col-10 col-sm-9 col-md-8 mx-auto py-4">
    <header>
        <h1 class="text-center text-primary">@ViewData["Title"]</h1>
        <hr />
    </header>
    @if (Model.Any())
    {
        <div class="row pt-2">
            @foreach(var role in Model)
            {
                <div class="col-11 col-md-6 col-lg-4 pr-md-3 mb-4">
                    <div class="card w-100">
                        <div class="card-header">
                            <small>ID: @role.Id</small>
                        </div>
                        <div class="card-body">
                            <h5 class="card-title mb-1">@role.Name</h5>
                        </div>
                        <div class="card-footer">
                            <a class="btn btn-sm btn-primary" 
                               asp-action="EditRole" asp-controller="Roles"
                               asp-route-id="@role.Id">Edit</a>
                            <a href="#" class="btn btn-sm btn-danger">Delete</a>
                        </div>
                    </div>
                </div>
            }
        </div>
        <div class="d-flex justify-content-center w-100 mt-5">
            <a asp-action="CreateRole" asp-controller="Roles" class="btn btn-sm btn-outline-primary">Create a new role +</a>
        </div>
    }
    else
    {
        <p class="text-center text-muted">You haven't created any rows</p>
        <a class="text-center" asp-action="CreateRole" asp-controller="Roles">Create a new row</a>
    }
</section>

JobApplicationBoard/Views/Roles/ManageRoleUsers.cshtml
@model List<UserRoleViewModel>

@{ 
    var roleId = ViewBag.roleId;
    ViewData["Title"] = "Manage users";
}


<section class="col-10 col-sm-9 col-md-6 col-lg-5 mx-auto py-4">
    <form asp-controller="Roles" asp-action="ManageRoleUsers" method="post">
        <div class="card">
            <div class="card-header">
                <h3>Manage users roles</h3>
                <p class="text-muted"><small>Assign users by checking the boxes</small></p>
            </div>
            <div class="card-body">
                @for(int i = 0; i < Model.Count; i++)
                {
                    <div class="form-check my-1">
                        <input type="hidden" asp-for="@Model[i].UserId" />
                        <input type="hidden" asp-for="@Model[i].UserName" />
                        <input asp-for="@Model[i].IsChecked" class="form-check-input"/>
                        <label class="form-check-label" asp-for="@Model[i].IsChecked">@Model[i].UserName</label>
                    </div>
                }
            </div>
            <div class="card-footer">
                <button type="submit" class="btn btn-primary mr-2" asp-route-roleid="@roleId">Update</button>
                <a asp-action="EditRole" asp-controller="Roles" 
                   asp-route-id="@roleId" class="btn btn-outline-danger">Discard changes</a>
            </div>
        </div>
    </form>
</section>